AllCops:
   NewCops: enable
   Exclude:
     - 'vendor/**/*'

Layout/IndentationWidth:
   Width: 3

Metrics/MethodLength:
   Max: 20

Style/TrailingCommaInHashLiteral:
   EnforcedStyleForMultiline: consistent_comma

